# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deck_options.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_DeckOptions(object):
    def setupUi(self, DeckOptions):
        DeckOptions.setObjectName("DeckOptions")
        DeckOptions.resize(318, 241)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeckOptions)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(DeckOptions)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 318, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollAreaLayout.setContentsMargins(6, 6, 6, 6)
        self.scrollAreaLayout.setObjectName("scrollAreaLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(DeckOptions)
        QtCore.QMetaObject.connectSlotsByName(DeckOptions)

    def retranslateUi(self, DeckOptions):
        _translate = QtCore.QCoreApplication.translate
        DeckOptions.setWindowTitle(_translate("DeckOptions", "DeckOptions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeckOptions = QtWidgets.QWidget()
    ui = Ui_DeckOptions()
    ui.setupUi(DeckOptions)
    DeckOptions.show()
    sys.exit(app.exec_())
