# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exclude_field_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExcludedFieldItem(object):
    def setupUi(self, ExcludedFieldItem):
        ExcludedFieldItem.setObjectName("ExcludedFieldItem")
        ExcludedFieldItem.resize(100, 42)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ExcludedFieldItem)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fieldLabel = QtWidgets.QLabel(ExcludedFieldItem)
        self.fieldLabel.setObjectName("fieldLabel")
        self.horizontalLayout.addWidget(self.fieldLabel)
        self.removeButton = QtWidgets.QPushButton(ExcludedFieldItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        self.removeButton.setStyleSheet(":active { border-style: outset;}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/remove_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon)
        self.removeButton.setFlat(True)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout.addWidget(self.removeButton)

        self.retranslateUi(ExcludedFieldItem)
        QtCore.QMetaObject.connectSlotsByName(ExcludedFieldItem)

    def retranslateUi(self, ExcludedFieldItem):
        _translate = QtCore.QCoreApplication.translate
        ExcludedFieldItem.setWindowTitle(_translate("ExcludedFieldItem", "Form"))
        self.fieldLabel.setText(_translate("ExcludedFieldItem", "SampleText"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExcludedFieldItem = QtWidgets.QWidget()
    ui = Ui_ExcludedFieldItem()
    ui.setupUi(ExcludedFieldItem)
    ExcludedFieldItem.show()
    sys.exit(app.exec_())
