# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.setWindowModality(QtCore.Qt.WindowModal)
        OptionsDialog.resize(279, 353)
        self.optionsLayout = QtWidgets.QVBoxLayout(OptionsDialog)
        self.optionsLayout.setObjectName("optionsLayout")
        self.OptionsScrollArea = QtWidgets.QScrollArea(OptionsDialog)
        self.OptionsScrollArea.setWidgetResizable(True)
        self.OptionsScrollArea.setObjectName("OptionsScrollArea")
        self.OptionsScrollWidget = QtWidgets.QWidget()
        self.OptionsScrollWidget.setGeometry(QtCore.QRect(0, 0, 259, 86))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OptionsScrollWidget.sizePolicy().hasHeightForWidth())
        self.OptionsScrollWidget.setSizePolicy(sizePolicy)
        self.OptionsScrollWidget.setObjectName("OptionsScrollWidget")
        self.optionsScrollLayout = QtWidgets.QVBoxLayout(self.OptionsScrollWidget)
        self.optionsScrollLayout.setObjectName("optionsScrollLayout")
        self.toolsOptionsCheckBox = QtWidgets.QCheckBox(self.OptionsScrollWidget)
        self.toolsOptionsCheckBox.setChecked(True)
        self.toolsOptionsCheckBox.setObjectName("toolsOptionsCheckBox")
        self.optionsScrollLayout.addWidget(self.toolsOptionsCheckBox)
        self.almostMarkCheckbox = QtWidgets.QCheckBox(self.OptionsScrollWidget)
        self.almostMarkCheckbox.setChecked(True)
        self.almostMarkCheckbox.setObjectName("almostMarkCheckbox")
        self.optionsScrollLayout.addWidget(self.almostMarkCheckbox)
        self.almostPosLayout = QtWidgets.QFormLayout()
        self.almostPosLayout.setHorizontalSpacing(64)
        self.almostPosLayout.setObjectName("almostPosLayout")
        self.almostLabel = QtWidgets.QLabel(self.OptionsScrollWidget)
        self.almostLabel.setObjectName("almostLabel")
        self.almostPosLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.almostLabel)
        self.almostPosDropdown = QtWidgets.QComboBox(self.OptionsScrollWidget)
        self.almostPosDropdown.setObjectName("almostPosDropdown")
        self.almostPosDropdown.addItem("")
        self.almostPosDropdown.addItem("")
        self.almostPosDropdown.addItem("")
        self.almostPosLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.almostPosDropdown)
        self.optionsScrollLayout.addLayout(self.almostPosLayout)
        self.OptionsScrollArea.setWidget(self.OptionsScrollWidget)
        self.optionsLayout.addWidget(self.OptionsScrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(OptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.optionsLayout.addWidget(self.buttonBox)

        self.retranslateUi(OptionsDialog)
        self.buttonBox.accepted.connect(OptionsDialog.accept)
        self.buttonBox.rejected.connect(OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialog.setWindowTitle(_translate("OptionsDialog", "Leech Toolkit"))
        self.toolsOptionsCheckBox.setText(_translate("OptionsDialog", "Show options in Tools menu"))
        self.almostMarkCheckbox.setText(_translate("OptionsDialog", "Show marker on about-to-be-leeched cards"))
        self.almostLabel.setText(_translate("OptionsDialog", "Marker Position"))
        self.almostPosDropdown.setItemText(0, _translate("OptionsDialog", "Default"))
        self.almostPosDropdown.setItemText(1, _translate("OptionsDialog", "Left"))
        self.almostPosDropdown.setItemText(2, _translate("OptionsDialog", "Right"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptionsDialog = QtWidgets.QDialog()
    ui = Ui_OptionsDialog()
    ui.setupUi(OptionsDialog)
    OptionsDialog.show()
    sys.exit(app.exec_())
